"""
Single source of truth for Gate 2's confirmation threshold.
Auto-generated by recompute_threshold.py -- Cohen's (1988) MEDIUM
effect-size convention (0.5 SD), last computed against n=662
messages, std dev=0.0506.
Reference: Cohen, J. (1988). Statistical Power Analysis for the
Behavioral Sciences (2nd ed.). Lawrence Erlbaum Associates.
"""

GATE2_CONFIRMATION_THRESHOLD = 0.02528
